
::: {.content-visible when-profile="english"}
# Practical 2
:::

::: {.content-visible when-profile="german"}
# Praktikum 2
:::



::: {.content-visible when-profile="english"}
In this session, we will cover the first steps in SPSS, including the descriptive analysis of a single variable and the (apparent) relationship between two variables. The following methods will be applied today:

-   **Graphical representations of quantitative variables**: bar charts, histograms, boxplots, and Q–Q plots
-   **Qualitative variables**: cross-tabulations, relative frequencies, risk difference, relative risk, and odds ratio
-   **Quantitative variables**: scatterplots, covariance, and correlation coefficient


### Practice exercises
📥 Download the dataset `nhanes30.sav` and open it in **SPSS** — either by drag and drop 🖱️ or via the File menu 🗂️ → Open.

::: {.download-card}
[Download recap for Practical 1](recap_P1.pdf){download="recap_P1.pdf"}
:::


:::

::: {.content-visible when-profile="german"}

In dieser Stunde geht es um die ersten Schritte in SPSS, die deskriptive Beschreibung eines Merkmals und eines (scheinbaren) Zusammenhangs zweier Merkmale. Folgende Verfahren kommen hierfür heute zur Anwendung:

-   **Grafische Darstellungen quantitativer Merkmale**: Balkendiagramme, Histogramme, Boxplots, Q-Q-Plots
-   **Qualitative Merkmale**: Kreuztabellen, relative Häufigkeiten, Risikodifferenz, Relatives Risiko, Odds Ratio
-   **Quantitative Merkmale**: Streudiagramme, Kovarianz, Korrelationskoeffizient

### Übungsaufgaben

📥 Laden Sie den Datensatz `nhanes30.sav` herunter und öffnen Sie diesen in **SPSS** —  entweder per drag & drop 🖱️  oder über das Auswahlmenü unter „Datei“ 🗂️ 

::: {.download-card}
[Zusammenfassung aus Praktikum 1 herunterladen](recap_P1.pdf){download="recap_P1.pdf"}
:::


:::

# Part 1: First Steps

{{< include part1.qmd >}}

# Part 2: Relationship between two variables

{{< include part2.qmd >}}
